version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - C64GOTD_ENV=dev
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
    depends_on:
      backend:
        condition: service_healthy

  test-frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: ["npm", "run", "test"]

  test-backend:
    build:
      context: ./backend
    command: ["pytest"]
    environment:
    - PYTHONPATH=/app
    - C64GOTD_ENV=test
    volumes:
      - ./backend:/app
    depends_on:
      backend:
        condition: service_started
