version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  test-frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: ["npm", "run", "test"]

  test-backend:
    build:
      context: ./backend
    command: ["pytest"]
    depends_on:
      - backend
